
import { GoogleGenAI } from "@google/genai";
// Fix: Use corrected relative import for core types
import { AspectRatio, ImageSize, ReferenceImage } from "../core/types.ts";

const VALID_ASPECT_RATIOS = new Set([
  '1:1', '2:3', '3:2', '3:4', '4:3', '4:5', '5:4', '9:16', '16:9', '21:9'
]);

// Fix: Exported missing constant for pipeline utility
export const NO_PACKAGING_NEGATIVE = "bottles, packaging, labels, product containers, text, logos, branding";

function dataUrlToPart(dataUrl: string) {
    const split = dataUrl.split(',');
    const base64Data = split[1];
    const mimeType = split[0].split(';')[0].split(':')[1];
    return {
        inlineData: {
            mimeType: mimeType,
            data: base64Data
        }
    };
}

/**
 * Helper to implement robust handling for API errors (e.g., 4xx/5xx) and unexpected responses.
 * Uses graceful retry logic with exponential backoff.
 */
async function withRetry<T>(
  operation: () => Promise<T>,
  signal?: AbortSignal,
  maxRetries: number = 3,
  baseDelay: number = 2000
): Promise<T> {
  let lastError: any;
  for (let i = 0; i < maxRetries; i++) {
    if (signal?.aborted) throw new DOMException('Aborted', 'AbortError');
    try {
      return await operation();
    } catch (error: any) {
      if (error.name === 'AbortError') throw error;
      lastError = error;
      // Retry on 503 Service Unavailable, 429 Too Many Requests, or generic "overloaded" message
      const isRetryable = error?.status === 503 || error?.status === 429 || error?.message?.toLowerCase().includes("overloaded");
      if (isRetryable && i < maxRetries - 1) {
        const delay = baseDelay * Math.pow(2, i);
        await new Promise(resolve => setTimeout(resolve, delay));
        continue;
      }
      throw error;
    }
  }
  throw lastError;
}

/**
 * Generates an image using Gemini models.
 * Follows @google/genai guidelines for image generation and model selection.
 */
export async function generateImageFromPrompt(params: {
  prompt: string;
  aspectRatio: AspectRatio;
  size: ImageSize;
  sourceAssetDataUrl?: string; 
  sourceAssetLabel?: string;
  referenceImages?: ReferenceImage[]; 
  model?: string;
  signal?: AbortSignal;
}): Promise<string> {
  return withRetry(async () => {
    if (params.signal?.aborted) throw new DOMException('Aborted', 'AbortError');
    
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    let validAR = params.aspectRatio;
    if (!VALID_ASPECT_RATIOS.has(validAR)) validAR = '1:1';

    // Model Selection Rules (DEV MODE):
    // - Always use a non-pro image model to avoid paid-key gating while we finish the project.
    // - Any requested size is clamped to 1K.
    let modelName = params.model || 'gemini-2.5-flash-image';
    if (modelName.startsWith('gemini-3')) modelName = 'gemini-2.5-flash-image';
    const imageSize = '1K' as const;
const parts: any[] = [{ text: params.prompt }];
    
    if (params.sourceAssetDataUrl) {
      parts.push(dataUrlToPart(params.sourceAssetDataUrl));
    }
    
    if (params.referenceImages) {
      params.referenceImages.forEach(ref => {
        parts.push(dataUrlToPart(ref.dataUrl));
      });
    }

    const response = await ai.models.generateContent({
      model: modelName,
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: validAR as any,
          imageSize: imageSize as any, // clamped to 1K (dev mode)
        }
      }
    });

    const candidate = response.candidates?.[0];
    const partsOut = candidate?.content?.parts;
    if (!partsOut) throw new Error("No output content generated by the model.");

    // Find the image part as per guidelines (iterate through parts)
    for (const part of partsOut) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image data found in the model response.");
  }, params.signal);
}

// Fix: Exported missing generateAvatar for ToolsModule integration
export async function generateAvatar(params: {
  aspectRatio: AspectRatio;
  baseStyleRules: string;
  contextRules: string;
  roleRules: string;
  enableRefs: boolean;
  allowMirrors: boolean;
  strictIdentity: boolean;
  creativityLevel: number;
  subjectA?: { dataUrl: string; label: string };
  subjectB?: { dataUrl: string; label: string };
  background?: { dataUrl: string; label: string };
  styleRefs?: { dataUrl: string; label: string }[];
  userPrompt?: string;
  signal?: AbortSignal;
}): Promise<string> {
  const prompt = `High-end professional portrait. 
Style: ${params.baseStyleRules}. 
Context: ${params.contextRules}. 
Role: ${params.roleRules}. 
${params.userPrompt ? `Extra constraints: ${params.userPrompt}` : ''}
${params.allowMirrors ? '' : 'Strictly avoid mirrors or reflective glass in background.'}
${params.strictIdentity ? 'Maintain strict facial likeness of the person provided.' : ''}`;

  return generateImageFromPrompt({
    prompt,
    aspectRatio: params.aspectRatio,
    size: "1k",
    sourceAssetDataUrl: params.subjectA?.dataUrl,
    referenceImages: params.styleRefs,
    signal: params.signal
  });
}

// Fix: Exported missing generateSceneBackground for pipeline utility integration
export async function generateSceneBackground(params: {
  prompt: string;
  negativePrompt?: string;
  width: number;
  height: number;
  systemInstruction?: string;
}): Promise<string> {
  // Determine best fit aspect ratio
  const ratio = params.width / params.height;
  let ar: AspectRatio = "1:1";
  if (ratio > 1.35) ar = "16:9";
  else if (ratio < 0.75) ar = "9:16";
  else if (ratio > 1.15) ar = "4:3";
  else if (ratio < 0.85) ar = "3:4";

  return generateImageFromPrompt({
    prompt: `${params.prompt}. Negative prompt: ${params.negativePrompt || ''}`,
    aspectRatio: ar,
    size: "1k"
  });
}