/**
 * ProductShots — neutral catalog backgrounds, generated by code (no AI).
 *
 * Two studio variants:
 *  - "light" (vitrina): bone/off-white base with a soft cenital softbox gradient,
 *    brighter top-center, gently darker toward the lower edges. Never flat #FFFFFF
 *    (reads clinical).
 *  - "dark" (NSCF dark theme): charcoal/graphite base with a studio gradient plus a
 *    subtle halo behind the product zone so a dark product doesn't sink into the
 *    background. Never pure #000000 (reads funereal).
 *
 * Returns a PNG data URL sized to the requested aspect ratio.
 */

export type CatalogVariant = 'light' | 'dark';

const VARIANTS: Record<CatalogVariant, { baseTop: string; baseBottom: string }> = {
  light: { baseTop: '#FAF8F4', baseBottom: '#E6E2DA' },
  dark:  { baseTop: '#1A1A1C', baseBottom: '#0E0E10' },
};

// Long side of the generated canvas. Big enough for crisp packshots, light enough
// to composite in the browser without lag.
const LONG_SIDE = 1600;

/** Parse "W:H" → { w, h } sized so the long side is LONG_SIDE px. */
export function aspectToDimensions(aspectRatio: string): { w: number; h: number } {
  const [aw, ah] = aspectRatio.split(':').map((n) => Number(n));
  const rw = Number.isFinite(aw) && aw > 0 ? aw : 1;
  const rh = Number.isFinite(ah) && ah > 0 ? ah : 1;
  if (rw >= rh) {
    return { w: LONG_SIDE, h: Math.round((LONG_SIDE * rh) / rw) };
  }
  return { w: Math.round((LONG_SIDE * rw) / rh), h: LONG_SIDE };
}

export function makeCatalogBackground(params: {
  variant: CatalogVariant;
  width: number;
  height: number;
}): string {
  const { variant, width: W, height: H } = params;
  const canvas = document.createElement('canvas');
  canvas.width = Math.max(1, Math.round(W));
  canvas.height = Math.max(1, Math.round(H));
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('2D context not available for catalog background.');

  const colors = VARIANTS[variant];

  // 1) Vertical studio base: brighter top, darker bottom (simulates a cenital softbox).
  const vGrad = ctx.createLinearGradient(0, 0, 0, H);
  vGrad.addColorStop(0, colors.baseTop);
  vGrad.addColorStop(1, colors.baseBottom);
  ctx.fillStyle = vGrad;
  ctx.fillRect(0, 0, W, H);

  // 2) Radial "spot" of light around the product zone (upper-center).
  const cx = W / 2;
  const cy = H * 0.42;
  const inner = Math.min(W, H) * 0.12;
  const outer = Math.max(W, H) * 0.85;
  const rGrad = ctx.createRadialGradient(cx, cy, inner, cx, cy, outer);

  if (variant === 'light') {
    // Subtle bright bloom; fades to transparent so the vertical base shows at edges.
    rGrad.addColorStop(0, 'rgba(255,255,255,0.55)');
    rGrad.addColorStop(0.5, 'rgba(255,255,255,0.12)');
    rGrad.addColorStop(1, 'rgba(255,255,255,0)');
    ctx.fillStyle = rGrad;
    ctx.fillRect(0, 0, W, H);
    // Gentle vignette to keep lower edges from looking flat.
    const vig = ctx.createRadialGradient(cx, H * 0.95, inner, cx, H * 0.95, outer);
    vig.addColorStop(0, 'rgba(0,0,0,0)');
    vig.addColorStop(1, 'rgba(0,0,0,0.05)');
    ctx.fillStyle = vig;
    ctx.fillRect(0, 0, W, H);
  } else {
    // Dark: a warm-neutral separation halo behind the product so it doesn't merge.
    rGrad.addColorStop(0, 'rgba(120,120,130,0.32)');
    rGrad.addColorStop(0.45, 'rgba(70,70,80,0.10)');
    rGrad.addColorStop(1, 'rgba(0,0,0,0)');
    ctx.fillStyle = rGrad;
    ctx.fillRect(0, 0, W, H);
    // Deepen the lower edges for a grounded studio floor.
    const vig = ctx.createRadialGradient(cx, H * 0.92, inner, cx, H * 0.92, outer);
    vig.addColorStop(0, 'rgba(0,0,0,0)');
    vig.addColorStop(1, 'rgba(0,0,0,0.35)');
    ctx.fillStyle = vig;
    ctx.fillRect(0, 0, W, H);
  }

  return canvas.toDataURL('image/png');
}
